name: Build
on:
  push:
  pull_request:
  schedule:
    # Baue einmal am Tag um Änderungen in Libraries zu entdecken.
    - cron: '14 7 * * *'
jobs:
  build:
    name: Test compiling
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Compile all examples
      uses: ArminJo/arduino-test-compile@v2
      with:
        arduino-board-fqbn: esp32:esp32:esp32
        platform-url: https://dl.espressif.com/dl/package_esp32_index.json
        required-libraries: DallasTemperature,OneWire,U8g2,Adafruit Unified Sensor,Adafruit BMP280 Library
